trigger: 
-  master
-  release/*

variables:
-  template: template-variables.yaml

stages:
# Build Stage
-  template: build-stage.yml
   parameters: 
     projectName: $(projectName)
     vmImage: $(vmImage)
     buildConfiguration: $(buildConfiguration)
     runtime: $(runtime)
# Deployment Stage
-  template: deployment-stage.yml
   parameters: 
     projectName: $(projectName)
     vmImage: $(vmImage) 
     RuntimeStack: $(RuntimeStack)
     WebAppName: $(WebAppName)