trigger: 
-  master
-  release/*
-  features/*


stages:
# Build Stage
-  template: build-stage.yml
   
# Deployment Stage
-  template: deployment-stage.yml
   parameters: 
     projectName: $(projectName)
     vmImage: $(vmImage) 
     RuntimeStack: $(RuntimeStack)
     WebAppName: $(WebAppName)